### ISSUE TITLE
can you move this to `https://github.com/facebookincubator/pystemd/blob/master/pystemd/utils.py` "from pystemd.run import DynamicUser" should not work, if it works (i'm away from a real interpreter to try) its due the weird __module__ hack at the end of this file.

### ISSUE THREAD

**Issue by Muunan** [facebookincubator/pystemd#17]
can you move this to `https://github.com/facebookincubator/pystemd/blob/master/pystemd/utils.py` "from pystemd.run import DynamicUser" should not work, if it works (i'm away from a real interpreter to try) its due the weird __module__ hack at the end of this file.

_Originally posted by @aleivag in https://github.com/facebookincubator/pystemd/pull/14/files_

**Comment by davide125** [comment]
Closing per @aleivag
