### ISSUE TITLE
Consider relicensing pystemd away from BSD+Patents

### ISSUE THREAD

**Issue by Conan-Kudo** [facebookincubator/pystemd#18]
Would you guys consider relicensing pystemd away from BSD+Patents to either plain `BSD-3-Clause` or `LGPL-2.1+` (the same license as libsystemd, which is a dependency of this)?

The BSD+Patents license is confusing and concerning for us in the ManaTools project for leveraging the module.

**Comment by davide125** [comment]
We are discussing this internally, will comment here when we have an update.

**Comment by Conan-Kudo** [comment]
@davide125 To give you an idea of what we want to use this for: we're looking to remake the `manaservice` tool in Python for managing services, and it'd be great if we can use this module to simplify the work to do that. However, our developers are skittish about the current license, which prompted me to request it to be relicensed.

**Comment by davide125** [comment]
We have the go ahead from the lawyers to relicense this project to `LGPL-2.1+`. I'll make the necessary changes, and the next release will be under the new license.

**Comment by Conan-Kudo** [comment]
Excellent, thanks!
