### ISSUE TITLE
Release 0.7?

### ISSUE THREAD

**Issue by irregulator** [facebookincubator/pystemd#37]
When tried to build 0.6 for Debian unstable with latest python 3.8 I came across the problem with `_ast` module, https://salsa.debian.org/python-team/modules/pystemd/-/jobs/417548 , which seems to be resolved in 35d1e091f299a8b28f62d8a37d5cc87ec79ddb30

Please consider releasing a new version including the latest commits in master branch.
Thanks.

**Comment by malmond77** [comment]
Thanks for the feedback. I'll check into this and will see what's needed to make this happen.

**Comment by aleivag** [comment]
I'll schedule a release today :)

**Comment by aleivag** [comment]
so actually "today" means like 2 week in the future.... but anyway... new release... yay!!
