### ISSUE TITLE
Release .deb for ubuntu

### ISSUE THREAD

**Issue by Timple** [facebookincubator/pystemd#42]
I know we can install the pip package on ubuntu. But we have an interest in releasing a .deb package that depends on pystemd. Therefor it would be nice that this package is also released, e.g. under the name **python-pystemd**

So people can install using `apt-get install python-pystemd` instead of `pip install pystemd`.

Would you have an interest for this?

**Comment by aleivag** [comment]
I have not used Ubuntu in ages but... Isn't pystemd already in Ubuntu ?
Example https://packages.ubuntu.com/focal/python3-pystemd

**Comment by Timple** [comment]
Ah, you're right!
We are always using the latest LTS which is bionic at the moment. (Focal is not yet released).

I've put in a request at the maintainers to release for bionic: https://answers.launchpad.net/ubuntu/+source/pystemd/+question/689077

**Comment by davide125** [comment]
Thanks @Timple!

**Comment by Timple** [comment]
I know this project runs on ubuntu 18.04 (we're using it). But do you perhaps have a pointer on where this is made explicit? Because ubuntu focal uses 3.8 and ubuntu bionic uses 3.6.
