### ISSUE TITLE
EnableUnitFiles fails because Interactive authentification is required

### ISSUE THREAD

**Issue by Yuusha0** [facebookincubator/pystemd#56]
Trying to Enable unit with EnableUnitFiles fails with _pystemd.dbusexc.DBusInteractiveAuthorizationRequiredError_. I cannot find a way in pystemd to enable Interactive Authorization. 

You can find a test case here : [https://framabin.org/p/?d1d698c4f63daad7#nguiuyQ77FS4PIntbRr7RMTy5Lko/nNyAu//Z3M5Wyk=](https://framabin.org/p/?d1d698c4f63daad7#nguiuyQ77FS4PIntbRr7RMTy5Lko/nNyAu//Z3M5Wyk=).

This functionality is implemented in other python dbus like [dbus-next](https://github.com/altdesktop/python-dbus-next/blob/9ae2e755c57ae07d5ed0ed882c8143ad30f5b0b9/dbus_next/constants.py). And it is implemented in Perl too. You can found an example of usage in Perl [here]( https://github.com/manatools/manatools/blob/3e65044752f3c8e5b85e0db6d2c3657ca27605df/lib/ManaTools/Shared/Services.pm#L407).

**Comment by davide125** [comment]
cc @aleivag, it looks like this is handled upstream by https://www.freedesktop.org/software/systemd/man/sd_bus_message_set_allow_interactive_authorization.html

**Comment by aleivag** [comment]
i'll check when was that added to systemd interface ... if we implement that, that means that pystemd will stop working for older versions of systemd.

**Comment by davide125** [comment]
Looks like this goes back to 220, so it's probably ok: https://github.com/systemd/systemd/commit/c0765ddb74f20046c406a3ac99f34719d767f151

**Comment by rschwiebert** [comment]
I might be the only one who doesn't see this, but do the above three comments mean that there is now a workaround?  Could we elaborate on that, if so?

**Comment by davide125** [comment]
This is fixed in https://github.com/facebookincubator/pystemd/commit/505e2b55276a61821a61c43e22ddf108df3080c7
