### ISSUE TITLE
pystemd doesn't work with Python version 3.10.1

### ISSUE THREAD

**Issue by banool** [facebookincubator/pystemd#65]
The error:
```
Jan 14 09:36:06 salsal run.sh[14952]:     from pystemd.dbuslib import DBus, apply_signature
Jan 14 09:36:06 salsal run.sh[14952]: ImportError: /home/daniel/control_panel/myvenv/lib/python3.10/site-packages/pystemd/dbuslib.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

Versions:
```
$ sc --version
systemd 250 (250.2-2-arch)

$ python --version
Python 3.10.1
```

This is using https://aur.archlinux.org/packages/python-pystemd/, which is version 0.9.

I suspect this is due to https://github.com/cython/cython/issues/3876, where Cython has issues with the latest version of Python. This was apparently fixed in 0.29.22.

I'm trying to figure out now what version of Cython we use to see if that's the issue

**Comment by banool** [comment]
Okay so I built pystemd from source and it fixed it, instead of using the pystemd from the AUR. I guess we just need to upload a new version there.

**Comment by aleivag** [comment]
this was just a problem with AUR, and not with pystemd (even tho we dont currently test on py 3.10
