### ISSUE TITLE
Usage of LXML for faster performance

### ISSUE THREAD

**Issue by Glandos** [facebookincubator/pystemd#67]
I'm currently trying to build a tool for managing unused socket activated services using pystemd.

However, I found that the main performance hit was the XML parser (currently xml.dom.minidom). I modified `base.py` to use lxml.etree.fromstring instead and the overall performance is 2.6× times better when loading properties for all `'*.service` units of my running system.

I know that this bring an external dependency, but would you mind considering using lxml, maybe as an optional dependency?

**Comment by aleivag** [comment]
how is the build story around lxml these days?, i remember it been very bad on the 2010 the last time i tried to get it into a system...

i have no problem introducing a external that external dependency, just dont want folks to spend their days figuring out how to get lxml on a raspberrypi ... :)

**Comment by davide125** [comment]
This is probably fine, lxml is packaged in pretty much all notable distros nowadays, so it shouldn't be too much trouble to add it as a dependency. If we can make it so we can fallback on minidom if it's not available, even better.

**Comment by Glandos** [comment]
Thank you very much for your quick response.
