### ISSUE TITLE
pip package update

### ISSUE THREAD

**Issue by peterder72** [facebookincubator/pystemd#69]
The pip package (and 0.10 release in general) seems to be very out of date (last update October 2021), with the Systemd Unit "Start" function entirely missing in that old version. 

Could someone possibly create a new release and bump the pip package? I can compile and install the library manually, but would still be nice to be able to do it properly via pip.

**Comment by aleivag** [comment]
Yeah we tend to be pretty slow in updating pip, most folks just get this either from EPEL  or from source... but i agree with you we should update this too PIP... i'll try to do it this weekend ... thanks @peterder72 for flagging this :D

**Comment by jaymzh** [comment]
@aleivag should we just set up a gh action to do it on all merges?

**Comment by davide125** [comment]
Not on all merges, but probably whenever a release is tagged.

**Comment by ddibiasi** [comment]
Is there any progress on this front? I'm certain that most hobbyists get their libraries from PyPi.

**Comment by aleivag** [comment]
package updated :

https://pypi.org/project/pystemd/0.11.0/
